apiVersion: v1
kind: Service
metadata:
  name: scaletestapp
  labels:
    app: scaletestapp
spec:
  selector:
    app: scaletestapp
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP