apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-monitor
  labels:
    app: scaletestapp
    release: prometheus
spec:
  selector:
    matchLabels:
      app: scaletestapp
  endpoints:
    - port: http
      path: /metrics
      interval: 10s